apiVersion: apps/v1
kind: Deployment
metadata:
  name: commette-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commette
  template:
    metadata:
      labels:
        app: commette
    spec:
      containers:
      - name: commette
        image: demoacrtest.azurecr.io/commette:latest
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: commette-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: commette